name: CICD
run-name: Running
on:
  push:
    branches:
      - production
      - 'releases/**'

env:
  AWS_REGION: ap-northeast-2
  AWS_S3_BUCKET: makeclassfile
  AWS_CODE_DEPLOY_APPLICATION: cicd-class-interaction
  AWS_CODE_DEPLOY_GROUP: cicd-class-interaction-group

jobs:
  build-with-gradle:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout production branch
      uses: actions/checkout@v3
      with:
        ref: production
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'corretto'
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
    - name: Build project
      run: ./gradlew clean build -x test
    - name: List build directory
      run: ls -al build/libs  # 빌드된 파일 목록 확인
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-region: ${{ env.AWS_REGION }}
        aws-access-key-id: ${{ secrets.ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.SECRET_KEY }}
    - name: Upload to S3
      run: aws s3 cp build/libs/EchoProject-0.0.1-SNAPSHOT.jar s3://${{ env.AWS_S3_BUCKET }}/cicdtest/${{ github.sha }}.zip
    - name: Deploy to EC2
      run: |
        aws deploy create-deployment \
          --application-name ${{ env.AWS_CODE_DEPLOY_APPLICATION }} \
          --deployment-config-name CodeDeployDefault.AllAtOnce \
          --deployment-group-name ${{ env.AWS_CODE_DEPLOY_GROUP }} \
          --s3-location bucket=${{ env.AWS_S3_BUCKET }},key=cicdtest/${{ github.sha }}.zip,bundleType=zip
